// This file is auto-generated by TanStack Router on `bun run dev`
// Do not edit manually — re-run dev to regenerate

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as LoginRoute } from "./routes/login";
import { Route as AppRoute } from "./routes/app/index";
import { Route as AppDashboardRoute } from "./routes/app/dashboard";
import { Route as AppMissionsRoute } from "./routes/app/missions";
import { Route as AppProfileRoute } from "./routes/app/profile";

const AppRouteWithChildren = AppRoute.addChildren([
	AppDashboardRoute,
	AppMissionsRoute,
	AppProfileRoute,
]);

const routeTree = rootRoute.addChildren([
	IndexRoute,
	LoginRoute,
	AppRouteWithChildren,
]);

export { routeTree };
