// This file is auto-generated by TanStack Router on `bun run dev`
// Do not edit manually — re-run dev to regenerate

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";

const routeTree = rootRoute.addChildren([IndexRoute]);

export { routeTree };
